#!/bin/bash

if [ -z "${QA}" ]; then
  export QA="x"
fi

alias jrme='jira sprint list --current --plain -a $(jira me)'
alias jrall='jira issues list -a $(jira me)'
alias jrcat='jira issue view'
alias jra='jira issue assign'
alias jrmv='jira issues move'
alias jrrm="jira issues delete"
alias jric='jira issues create'
alias jrcm='jira issue comment add'
alias jrob='jira open'
alias jrcs='jira sprint list --current'
alias jrop='jira open'


# Move Jira task to QA
jrqa() {
  worker=${2:-$QA}

  jira issues move "$1" "$QA_STATUS"
  jira issues assign "$1" "$worker"
}
jrrw() {
  jira issues move $1 $REVIEW_STATUS
}

# Assign a task to yourself
jram() {
  jira issue assign "$1" $(jira me)
}

# Unassign a task
jrua() {
  jira issue assign "$1" x
}

# Mark task as done
jrdone() {
  jrmv "$1" "$DONE_STATUS"
  jrua "$1"
}
jready() {
  jrmv "$1" "$RELEASE_STATUS"
  jrua "$1"
}

jrpr() {
  jrmv "$1" "$PROGRESS_STATUS"
}


jrhelp() {
 cat <<EOF 
  Requirements:
    variable DONE_STATUS -> status of completion for the ticket (it is in prod & live)
    variable RELEASE_STATUS -> status of development completion for the ticket (it is in dev & live only in dev)
    variable QA -> email or identifier of QA (can be set to "x" for unassignment) 
    variable REVIEW_STATUS -> the state in which tasks are set for review
    variable PROGRESS_STATUS -> the state in which tasks actively worked on

  Commands:
    jrme   - Current sprint tasks assigned to you
    jrall  - All tasks assigned to you
    jrcat  - Get details on a task
    jra    - Assign a task
    jrmv   - Move task 
    jrrm   - Delete task
    jric   - Create task
    jrcm   - Comment on a task
    jrob   - Open jira board
    jrcs   - List current sprint
    jrrw   - Set task for review
    jrpr   - Set task for as "currently worked on"o
    jrop   - Open Jira
    
    jrqa   - Send task and assign to QA 
    jram   - Assign task to me 
    jrua   - Unassign task from me
    jrdone - Set task as Done
    jrhelp - Show commands
EOF

}
alias jr='jrhelp'
